# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
# target 'GrabMotion' do
# end

platform :ios, '9.0'
use_frameworks!

link_with 'GrabMotion'
target "GrabMotion" do
pod 'Alamofire', '~> 3.0'
#pod 'ProtocolBuffers-Swift'
pod 'ProtocolBuffers-Swift', :git => 'https://github.com/alexeyxo/protobuf-swift.git', :branch => 'ProtoBuf3.0-Swift2.0'
pod 'Parse'
pod 'ParseFacebookUtilsV4'
pod 'ParseTwitterUtils'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'SVProgressHUD'
pod 'AlamofireOauth2', '~> 1.0'
pod 'OpenCV', '2.4.9'
pod 'KYCircularProgress'
end


