# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
# target 'GrabMotion' do
# end

platform :ios, '9.0'
use_frameworks!

link_with 'GrabMotion'
target "GrabMotion" do
pod 'Alamofire', '~> 3.0'
pod 'ProtocolBuffers-Swift'
end


